### ISSUE TITLE
Not compatible with HD skins

### ISSUE THREAD

**Issue by AdminHcat** [RiskyKen/Armourers-Workshop#333]
Not compatible with HD skin(Skin resolution 1024*512) of CustomSkinLoader mod，Will appear as a transparent skin

（Please excuse me for my poor English）

**Comment by GedeonGrays** [comment]
I fully confirm @AdminHcat's problem.

_Basic information:_
**Minecraft version:** 1.7.10
**Armourer's Workshop version:** 1.7.10-0.48.5

_Additional information:_ testing was carried out on several clients of the game. In some cases there was a transparent texture, in others it was completely black texture. No other mods have been installed. The game assets have _**not**_ been modified.

**Comment by RiskyKen** [comment]
HD skins are not supported in the 1.7.10 version of the mod and probably never will be because it's not getting big updates anymore.

You can ether:

1 Turn of texture painting in the config `config\armourersWorkshop\client.cfg` set `texturePainting=2`. (Armourer's Workshop will lose some of it's functionality doing this)

2 Remove the mod that adds HD skins!

**Comment by GedeonGrays** [comment]
> HD skins are not supported in the 1.7.10 version of the mod and probably never will be because it's not getting big updates anymore.
> 
> You can ether:
> 
> 1 Turn of texture painting in the config `config\armourersWorkshop\client.cfg` set `texturePainting=2`. (Armourer's Workshop will lose some of it's functionality doing this)
> 
> 2 Remove the mod that adds HD skins!

Hmm ... sad. At least tell me, what functionality will AW lose with the first option?
