### ISSUE TITLE
[Feature] [Could be denied] How do you think about rewriting this mod onto newer minecraft versions?

### ISSUE THREAD

**Issue by JeonDohyeon** [RiskyKen/Armourers-Workshop#370]
**Is your feature request related to a problem? Please describe.**
This request is not related to any of the problem, but hey, there's no custom 3D texture loader on newer versions, only 2D flat.

**Describe the solution you'd like**
I think rewriting this mod onto 1.16.5 since the Forge and Forge-based mods that have 1.12.2 versions have completely different codes and assets. Almost nothing is in-common, as other mod devs think.

**Describe alternatives you've considered**
On this, there's no alternatives. 1.13(called Aquatic Update) has bunches of changes of codes, and 1.16(Nether Update) has other bunch, removing item nums and more.

**Additional context**
No additional context(s). This is just a thing that asking you if you have thought the differences of codes between 1.12 and 1.16, like between 1.7 and 1.12.

**Comment by DoomRater** [comment]
Here is a workaround: Customizable Player Models.  Not only is it compatible with Armourer's Workshop in 1.12.2, but it has updated as well.  I'm mentioning this because there are no current plans to undertake a complete rewrite of the code to update AW beyond 1.12.2 at the moment.  

Before dismissing CPM as a 2D creation tool, consider it can also create animations in an easier fashion than custom Quark emotes.  Also I am fairly sure it can use full 3D objects in its creation process.

There is another workaround if you still want Armourer's Workshop with updated features: Aqua Acrobatics back ports swimming and crawling to 1.12.2, and Future MC will offer Nether Block generation along with working trident and enchantments for the trident as well.  Between these two mods, they may tide you over until Risky is capable of rewriting the mod.

**Comment by JeonDohyeon** [comment]
Ok, I'll close this
